
export default {
  CommitCommentEvent: 'commented on commit',
  CreateEvent: event => `created ${event.payload.ref_type} on`,
  DeleteEvent: 'deleted',
  DeploymentEvent: '',
  DeploymentStatusEvent: '',
  DownloadEvent: '',
  FollowEvent: '',
  ForkEvent: 'forked',
  ForkApplyEvent: '',
  GistEvent: '',
  GollumEvent: '',
  IssueCommentEvent: 'commented on issue',
  IssuesEvent: 'created issue on',
  MemberEvent: '',
  MembershipEvent: '',
  PageBuildEvent: '',
  PublicEvent: '',
  PullRequestEvent: 'created pr',
  PullRequestReviewCommentEvent: 'commented on pr',
  PushEvent: 'pushed',
  ReleaseEvent: '',
  RepositoryEvent: '',
  StatusEvent: '',
  TeamAddEvent: '',
  WatchEvent: 'starred',
};
